# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 'lts/*'
cache: yarn
env:
  global:
  - ENCRYPTED_VARIABLE_TOKEN: "a36f85be0be9"
  - COMMIT_AUTHOR_EMAIL: "kubevirt-builder@redhat.com"
  - COMMIT_AUTHOR_NAME: "KubeVirt Builder"
notifications:
  email: false
before_install:
  # install and use the latest version of Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  # start ssh-agent in the background
  - eval `ssh-agent -s`
install:
  - yarn install
before_script:
  - node tools/travis/beforeScript.js
script:
  - yarn build
  - yarn coveralls
after_success:
  - node tools/travis/afterSuccess.js
