export const POD_STATUS_NOT_SCHEDULABLE = 'POD_NOT_SCHEDULABLE';
export const POD_STATUS_CONTAINER_FAILING = 'POD_CONTAINER_FAILING';
export const POD_STATUS_NOT_READY = 'POD_NOT_READY';
export const POD_STATUS_READY = 'POD_READY';

export const POD_STATUS_ALL_ERROR = [POD_STATUS_NOT_SCHEDULABLE, POD_STATUS_CONTAINER_FAILING];
export const POD_STATUS_ALL_PROGRESS = [POD_STATUS_NOT_READY];
