export const PVC_STATUS_PENDING = 'PVC_STATUS_PENDING';
export const PVC_STATUS_BOUND = 'PVC_STATUS_BOUND';
export const PVC_STATUS_LOST = 'PVC_STATUS_LOST';
export const PVC_STATUS_DEFAULT = 'PVC_STATUS_DEFAULT';

export const PVC_STATUS_ALL_ERROR = [PVC_STATUS_LOST];
export const PVC_STATUS_ALL_PROGRESS = [PVC_STATUS_PENDING];
