export const NODE_STATUS_OUT_OF_DISK = 'NODE_OUT_OF_DISK';
export const NODE_STATUS_NETWORK_UNAVAILABLE = 'NODE_NETWORK_UNAVAILABLE';

export const NODE_STATUS_NOT_READY = 'NODE_STATUS_NOT_READY';
export const NODE_STATUS_NOT_RESPONDING = 'NODE_STATUS_NOT_RESPONDING';

export const NODE_STATUS_MEMORY_PRESSURE = 'NODE_MEMORY_PRESSURE';
export const NODE_STATUS_PID_PRESSURE = 'NODE_PID_PRESSURE';
export const NODE_STATUS_DISK_PRESSURE = 'NODE_DISK_PRESSURE';

export const NODE_STATUS_READY = 'NODE_STATUS_READY';

export const NODE_STATUS_ALL_ERROR = [
  NODE_STATUS_OUT_OF_DISK,
  NODE_STATUS_NETWORK_UNAVAILABLE,
  NODE_STATUS_NOT_READY,
  NODE_STATUS_NOT_RESPONDING,
];
export const NODE_STATUS_ALL_WARN = [NODE_STATUS_MEMORY_PRESSURE, NODE_STATUS_PID_PRESSURE, NODE_STATUS_DISK_PRESSURE];
