export const MEDIA_QUERY_XS = 0;
export const MEDIA_QUERY_SM = 576;
export const MEDIA_QUERY_MD = 768;
export const MEDIA_QUERY_LG = 992;
export const MEDIA_QUERY_XL = 1200;

export const MEDIA_QUERY_ALL_CLASSES = [MEDIA_QUERY_XS, MEDIA_QUERY_SM, MEDIA_QUERY_MD, MEDIA_QUERY_LG, MEDIA_QUERY_XL];

export const MEDIA_QUERY_EXCLUSIVE_DEVIATION = 0.1;
