export const DEPLOYMENT_STATUS_PROGRESSING = 'DEPLOYMENT_STATUS_PROGRESSING';
export const DEPLOYMENT_STATUS_ROLLOUT_COMPLETE = 'DEPLOYMENT_STATUS_ROLLOUT_COMPLETE';
export const DEPLOYMENT_STATUS_FAILED = 'DEPLOYMENT_STATUS_FAILED';
export const DEPLOYMENT_STATUS_UNKNOWN = 'DEPLOYMENT_STATUS_UNKNOWN';

export const DEPLOYMENT_ALL_PROGRESS = [DEPLOYMENT_STATUS_PROGRESSING];
export const DEPLOYMENT_ALL_ERROR = [DEPLOYMENT_STATUS_FAILED];
