export const PV_STATUS_AVAILABLE = 'PV_STATUS_AVAILABLE';
export const PV_STATUS_BOUND = 'PV_STATUS_BOUND';
export const PV_STATUS_RELEASED = 'PV_STATUS_RELEASED';
export const PV_STATUS_FAILED = 'PV_STATUS_FAILED';
export const PV_STATUS_DEFAULT = 'PV_STATUS_DEFAULT';

export const PV_STATUS_ALL_ERROR = [PV_STATUS_FAILED];
export const PV_STATUS_ALL_PROGRESS = [PV_STATUS_AVAILABLE];
